#ifndef MID_WEATHER_SCENE_H
#define MID_WEATHER_SCENE_H

#include "platform_common.h"

typedef enum 
{
	WEATHER_TENDENCY_SUNNY 				= 0x0000,
	WEATHER_TENDENCY_CLOUDY,
	WEATHER_TENDENCY_OVERCAST,
	WEATHER_TENDENCY_HAZE,
	WEATHER_TENDENCY_ICERAIN,
	WEATHER_TENDENCY_FOGGY,
    
	WEATHER_TENDENCY_LIGHT_RAIN 		= 0x0100,
	WEATHER_TENDENCY_MODERATE_RAIN,
	WEATHER_TENDENCY_HEAVY_RAIN,
	WEATHER_TENDENCY_RAINSTORM,
	WEATHER_TENDENCY_BIG_RAINSTORM,
	WEATHER_TENDENCY_SUPER_RAINSTORM,
    
	WEATHER_TENDENCY_SNOW_SHOWER 		= 0x0200,
	WEATHER_TENDENCY_LIGHT_SNOW,
	WEATHER_TENDENCY_MODERATE_SNOW,
	WEATHER_TENDENCY_HEAVY_SNOW,
	WEATHER_TENDENCY_BLIZZARD ,
    
	WEATHER_TENDENCY_DUST        		=0x0300,
	WEATHER_TENDENCY_DUSTBLOW,
	WEATHER_TENDENCY_SANDSTORM,
	WEATHER_TENDENCY_STRONG_SANDSTORM,
    
	WEATHER_TENDENCY_SHOWER     		=0x0400,
	WEATHER_TENDENCY_THUNDER_RAIN,
	WEATHER_TENDENCY_SLEETY,
	WEATHER_TENDENCY_HAIL,
    
	WEATHER_TENDENCY_NO_INFO 			= 0xFFFF		// 无天气信息
}eWeatherStatus;	

//weather:记录天气预报，来自手机APP下发
typedef struct 
{
	eWeatherStatus 		Status;
	int8 				CurTemperature;
	int8 				MaxTemperature;
	int8 				MinTemperature;
}Mid_Weahter_Param_t;

uint16 Mid_WeatherScene_Init(void);
uint16 Mid_WeatherScene_TendencyGet(Mid_Weahter_Param_t *weatherinfo);
uint16 Mid_WeatherScene_TendencySet(Mid_Weahter_Param_t *weatherinfo);

#endif


